export const GET_CHARACTERS_PENDING = 'GET_CHARACTERS_PENDING';
export const GET_CHARACTERS_SUCCESS = 'GET_CHARACTERS_SUCCESS';
export const GET_CHARACTERS_SEARCH = 'GET_CHARACTERS_SEARCH';
export const GET_CHARACTERS_FAILURE = 'GET_CHARACTERS_FAILURE';
